### ISSUE TITLE
Fix DESCRIPTION file with IMPORTS version

### ISSUE THREAD

**Issue by raonirao** [kylebutts/ssaggregate#1]
Hi, Kyle!

Your DESCRIPTION file for 'ssaggregate' lists the package 'data.table' in the IMPORTS section, but leaves out a very important information: it appears that you are using the (as of now) unreleased data.table 1.14.3. You use the 'env' argument in `[.data.table]`, which did not yet exist on version 1.14.2 on CRAN.

It took me a while to sort it out on my own, because R throwed me an error for a an 'unused argument' for data.table. I would ask you to consider including this info on your description file, so that any errors of this kind occur at loading, making clear what is happening...

Cheers!

**Comment by kylebutts** [comment]
Thanks, I will do that. Very good point, thanks for flagging!
